### ISSUE TITLE
能否考虑require时加上localstorage缓存？

### ISSUE THREAD

**Issue by jiajianrong** [fex-team/mod#31]
modjs先读ls，读不到的话再loadJS
把现在的&lt;script src=''a.js">&lt;/script>改成&lt;script>require.load("a.js")&lt;/script>

**Comment by xiangshouding** [comment]
参考 repos

https://github.com/xiangshouding/mod-store.js

需要结合 FIS 的一起用。

**Comment by jiajianrong** [comment]
多谢
