### ISSUE TITLE
mod.js 出现某一个id没有找到的情况

### ISSUE THREAD

**Issue by HBXSZ** [fex-team/mod#38]
具体情况是自己用nginx搭了一个本地环境，跑起来之后报错，代码 throw '[ModJS] Cannot find module `' + id + '`'; 切到浏览器里去看network选项没有加载该id对应的js文件，请问这是什么原因导致的？

**Comment by hefangshi** [comment]
mod.js不能加载动态的模块名，必须使用静态的模块名。或者搭配注释实现动态加载

```javascript
// @require 'a.js'
// @require 'b.js'

var a = 'a.js'
var A = require(a);
```

**Comment by HBXSZ** [comment]
@hefangshi  嗯，问题解决了
