### ISSUE TITLE
mod.js加载页面依赖文件报错

### ISSUE THREAD

**Issue by ClausClaus** [fex-team/mod#55]
使用mod.js加载页面脚本依赖时经常出现这样的报错问题，脚本文件是没问题的。出现报错之后再次刷新浏览器即可解决。这个是我的fis配置问题还是？求指教。。。 
![issue1](https://user-images.githubusercontent.com/21154310/36575953-b4d17fe2-1888-11e8-8f90-69320ed0d480.png)

![issue2](https://user-images.githubusercontent.com/21154310/36576039-29a946a6-1889-11e8-8ff6-9e6ebcac7872.png)

**Comment by oxUnd** [comment]
mod.js 第一个加载啊，不然就是 undefined。

**Comment by ClausClaus** [comment]
我的mod.js是第一个加载的。。。
- 这个是页面模块的layout.tpl，所有页面模块从这里引入最终解析加载
![issue3](https://user-images.githubusercontent.com/21154310/36599714-3b53270c-18eb-11e8-8895-20226fa3d350.png)
- 这个是某个加载后的页面文件，就算页面报错，mod.js也是第一个加载的。。。
![issue4](https://user-images.githubusercontent.com/21154310/36599960-edaa795a-18eb-11e8-9b93-bcb66fd36c83.png)
前端脚本肯定没问题，公司后端以前用的.net。没有这个问题。去年换了php，smarty模板引擎做的页面数据插入。页面脚本依赖就是这个mod.js。就开始有这个情况出现。页面结构特殊不使用我这个layout去引入加载的话也还是有这个问题，有点无解。。。真的刷新下页面脚本就加载进来了，请求给分析分析问题可能出在什么地方

**Comment by oxUnd** [comment]
看样子你没有按照。。smarty 解决方案去用啊，比如你的 $_map 这个你是怎么用的？
